version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:latest  # Using the CircleCI Node.js image
    steps:
      - checkout  # Check out the code from the version control system
      - run:
          name: Install Dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run Tests
          command: npm test  # Run your tests
      - run:
          name: Build Project
          command: npm run build  # Build your project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
